### ISSUE TITLE
Notification Receiver Engine via YAML configuration

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#18]
## Description

As an admin I want to be able to define who receives each notification

## Acceptance criteria

- [ ] Yaml file specifies the credential criteria to be used to retrieve the users that are eligible to receive notifications for each email template for each event type

## Additional Context

```yaml
recipients:
  application_created:
    admin:
      - rule:
          type: ChallengeAdmin
          resource_id: <challengeID>
      - rule:
          type: OpportunityAdmin
          resource_id: <opportunityID>
      - rule:
          type: EcoverseAdmin
          resource_id: <ecoverseID>
      - rule:
          type: GlobalAdmin
          resource_id: <>
    applicant:
      - rule:
          type: UserSelfManagement
          resource_id: <applicantID>
```
